import { Platform } from 'react-native';

import { makeTheme } from 'dripsy';

const fontName = 'pretendard';
const webFont = (font: string) =>
  Platform.select({
    web: `${font}, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, Inter-serif`,
    default: font,
  });

const theme = makeTheme({
  colors: {
    $primary: '#E51111',
    $black: '#02071B',
    $background: '#151B33',
    $grey: '#7D818D',
    $lightgrey: '#BEC2CF',
    $white: '#FFFFFF',
    $dimLayer: '#02071B61',
    $liveRed: '#E51111',
  },
  space: {
    $0: 0,
    $1: 4,
    $2: 8,
    $3: 16,
    $4: 32,
    $5: 64,
    $6: 128,
    $7: 256,
  },
  customFonts: {
    [fontName]: {
      default: webFont('Pretendard-Light'),
      light: webFont('Pretendard-Light'),
      bold: webFont('Pretendard-Bold'),
      black: webFont('Pretendard-Black'),
      400: webFont('Pretendard-Light'),
      700: webFont('Pretendard-Bold'),
      900: webFont('Pretendard-Black'),
    },
  },
  fonts: {
    root: fontName,
  },
  fontWeights: {
    light: '400',
    bold: '700',
    black: '900',
  },
  text: {
    Text10BoldBlackCenter: {
      fontWeight: 'bold',
      textAlign: 'center',
      fontSize: 10,
      lineHeight: 15,
      color: '$black',
    },
    Text10LightBlackCenter: {
      fontWeight: 'light',
      textAlign: 'center',
      fontSize: 10,
      lineHeight: 15,
      color: '$black',
    },
    Text21BlackBlack: {
      fontWeight: 'black',
      textAlign: 'left',
      fontSize: 21,
      lineHeight: 32,
      color: '$black',
    },
    Text16BoldBlackCenter: {
      fontWeight: 'bold',
      textAlign: 'center',
      fontSize: 16,
      lineHeight: 24,
      color: '$black',
    },
    Text16BoldWhiteCenter: {
      fontWeight: 'bold',
      textAlign: 'center',
      fontSize: 16,
      lineHeight: 24,
      color: '$white',
    },
    Text14BoldBlack: {
      fontWeight: 'bold',
      textAlign: 'left',
      fontSize: 14,
      lineHeight: 21,
      color: '$black',
    },
    Text12LightGrey: {
      fontWeight: 'light',
      textAlign: 'left',
      fontSize: 12,
      lineHeight: 18,
      color: '$grey',
    },
    Text10BoldWhiteCenter: {
      fontWeight: 'bold',
      textAlign: 'center',
      fontSize: 10,
      lineHeight: 15,
      color: '$white',
    },
    Text12BoldWhiteCenter: {
      fontWeight: 'bold',
      textAlign: 'center',
      fontSize: 12,
      lineHeight: 18,
      color: '$white',
    },
    Text12LightWhiteCenter: {
      fontWeight: 'light',
      textAlign: 'center',
      fontSize: 12,
      lineHeight: 18,
      color: '$white',
    },
    Text14LightBlack: {
      fontWeight: 'light',
      textAlign: 'left',
      fontSize: 14,
      lineHeight: 21,
      color: '$black',
    },
    Text14LightGreyCenter: {
      fontWeight: 'light',
      textAlign: 'center',
      fontSize: 14,
      lineHeight: 21,
      color: '$grey',
    },
    Text12BoldGreyCenter: {
      fontWeight: 'bold',
      textAlign: 'center',
      fontSize: 12,
      lineHeight: 18,
      color: '$grey',
    },
    Text16BoldLightgrey: {
      fontWeight: 'bold',
      textAlign: 'left',
      fontSize: 16,
      lineHeight: 24,
      color: '$lightgrey',
    },
    Text14LightLightgrey: {
      fontWeight: 'light',
      textAlign: 'left',
      fontSize: 14,
      lineHeight: 21,
      color: '$lightgrey',
    },
    Text16BoldBlack: {
      fontWeight: 'bold',
      textAlign: 'left',
      fontSize: 16,
      lineHeight: 24,
      color: '$black',
    },
    Text12BoldBlackCenter: {
      fontWeight: 'bold',
      textAlign: 'center',
      fontSize: 12,
      lineHeight: 18,
      color: '$black',
    },
    Text18BoldBlack: {
      fontWeight: 'bold',
      textAlign: 'left',
      fontSize: 18,
      lineHeight: 27,
      color: '$black',
    },
    Text16LightLightgrey: {
      fontWeight: 'light',
      textAlign: 'left',
      fontSize: 16,
      lineHeight: 24,
      color: '$lightgrey',
    },
    Text24BlackBlackCenter: {
      fontWeight: 'black',
      textAlign: 'center',
      fontSize: 24,
      lineHeight: 36,
      color: '$black',
    },
    Text12LightGreyCenter: {
      fontWeight: 'light',
      textAlign: 'center',
      fontSize: 12,
      lineHeight: 18,
      color: '$grey',
    },
    Text14BoldBlackCenter: {
      fontWeight: 'bold',
      textAlign: 'center',
      fontSize: 14,
      lineHeight: 21,
      color: '$black',
    },
    Text24BlackWhite: {
      fontWeight: 'black',
      textAlign: 'left',
      fontSize: 24,
      lineHeight: 36,
      color: '$white',
    },
    Text18BoldWhite: {
      fontWeight: 'bold',
      textAlign: 'left',
      fontSize: 18,
      lineHeight: 27,
      color: '$white',
    },
    Text21BlackWhite: {
      fontWeight: 'black',
      textAlign: 'left',
      fontSize: 21,
      lineHeight: 32,
      color: '$white',
    },
    Text14BoldWhite: {
      fontWeight: 'bold',
      textAlign: 'left',
      fontSize: 14,
      lineHeight: 21,
      color: '$white',
    },
    Text12LightLightgrey: {
      fontWeight: 'light',
      textAlign: 'left',
      fontSize: 12,
      lineHeight: 18,
      color: '$lightgrey',
    },
    Text14LightWhite: {
      fontWeight: 'light',
      textAlign: 'left',
      fontSize: 14,
      lineHeight: 21,
      color: '$white',
    },
    Text16BoldWhite: {
      fontWeight: 'bold',
      textAlign: 'left',
      fontSize: 16,
      lineHeight: 24,
      color: '$white',
    },
    Text48BlackWhiteCenter: {
      fontWeight: 'black',
      textAlign: 'center',
      fontSize: 48,
      lineHeight: 48,
      color: '$white',
    },
    Text24BlackWhiteCenter: {
      fontWeight: 'black',
      textAlign: 'center',
      fontSize: 24,
      lineHeight: 36,
      color: '$white',
    },
    Text24LightWhiteCenter: {
      fontWeight: 'light',
      textAlign: 'center',
      fontSize: 24,
      lineHeight: 36,
      color: '$white',
    },
    Text18BoldWhiteCenter: {
      fontWeight: 'bold',
      textAlign: 'center',
      fontSize: 18,
      lineHeight: 27,
      color: '$white',
    },
    Text16LightLightgreyCenter: {
      fontWeight: 'light',
      textAlign: 'center',
      fontSize: 16,
      lineHeight: 24,
      color: '$lightgrey',
    },
    Text16LightGrey: {
      fontWeight: 'light',
      textAlign: 'left',
      fontSize: 16,
      lineHeight: 24,
      color: '$grey',
    },
    Text14LightGrey: {
      fontWeight: 'light',
      textAlign: 'left',
      fontSize: 14,
      lineHeight: 21,
      color: '$grey',
    },
    Text16BoldGrey: {
      fontWeight: 'bold',
      textAlign: 'left',
      fontSize: 16,
      lineHeight: 24,
      color: '$grey',
    },
    Text16BoldGreyCenter: {
      fontWeight: 'bold',
      textAlign: 'center',
      fontSize: 16,
      lineHeight: 24,
      color: '$grey',
    },
    Text16LightGreyCenter: {
      fontWeight: 'light',
      textAlign: 'center',
      fontSize: 16,
      lineHeight: 24,
      color: '$grey',
    },
    Text16LightWhiteCenter: {
      fontWeight: 'light',
      textAlign: 'center',
      fontSize: 16,
      lineHeight: 24,
      color: '$white',
    },
    Text12LightWhite: {
      fontWeight: 'light',
      textAlign: 'left',
      fontSize: 12,
      lineHeight: 18,
      color: '$white',
    },
    Text16BoldWhiteRight: {
      fontWeight: 'bold',
      textAlign: 'right',
      fontSize: 16,
      lineHeight: 24,
      color: '$white',
    },
    Text16BoldGreyRight: {
      fontWeight: 'bold',
      textAlign: 'right',
      fontSize: 16,
      lineHeight: 24,
      color: '$grey',
    },
    Text14BoldWhiteCenter: {
      fontWeight: 'bold',
      textAlign: 'center',
      fontSize: 14,
      lineHeight: 21,
      color: '$white',
    },
    Text16LightWhite: {
      fontWeight: 'light',
      textAlign: 'left',
      fontSize: 16,
      lineHeight: 24,
      color: '$white',
    },
    Text14BoldGreyCenter: {
      fontWeight: 'bold',
      textAlign: 'center',
      fontSize: 14,
      lineHeight: 21,
      color: '$grey',
    },
  },
});

type MyTheme = typeof theme;

declare module 'dripsy' {
  interface DripsyCustomTheme extends MyTheme {}
}

export { theme };
